### PR TITLE
README: Added content.

### PR DESCRIPTION
**Pull request by EricDunsworth**
Fixes wet-boew/wet-boew#6180.

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
@thomasgohard can you get this translated?

**Comment by thomasgohard** [comment]
I'll translate it myself. Won't take long.

I'll convert this into a feature branch and add the French.

**Comment by LaurentGoderre** [comment]
@thomasgohard my bad, I didn't think you needed the .md. You will need to rename the file

**Comment by thomasgohard** [comment]
Ah. That explains what I'm seeing. OK. Fixing that in a new pull request.

**Comment by thomasgohard** [comment]
Fixed in #5.

**Pull request merged**
